In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns
sns.set()

This code shows how we extracted lumA IDC and lumA IDC samples for part 4.2.4 of the project: **Comparison between lumA ILC and lumA IDC**.

## 1-  Extraction of the luminal A patients  (IDC & ILC)

In [3]:
# read data (tableS1 from the article)
data_A = pd.read_excel('data/lumA.xlsx',header=1,skiprows=range(0, 1))

data_A.head(3)

,Case.ID,Final Pathology,PAM50,TumorPurity,ProliferationScore,mRNA,miRNA,SNP,Exome,Methylation,...,Hormone_a score,Hormone_b score,PI3K/Akt score,Ras/MAPK score,RTK score,TSC/mTOR score,ISOpure,OncoSign,ElasticNet,Unnamed: 27
0,TCGA-BH-A18G,IDC,Basal,0.79,0.423067,TCGA-BH-A18G-01A-11R-A12D-07,TCGA-BH-A18G-01A-11R-A12C-13,TCGA-BH-A18G-01A-11D-A12A-01,TCGA-BH-A18G-01A-11D-A12B-09,TCGA-BH-A18G-01A-11D-A12E-05,...,-1.873243,-0.120416,-3.469006,0.943580,-1.421711,1.376493,NaN,NaN,NaN,IDC-like
1,TCGA-A1-A0SP,IDC,Basal,0.46,0.262933,TCGA-A1-A0SP-01A-11R-A084-07,TCGA-A1-A0SP-01A-11R-A085-13,TCGA-A1-A0SP-01A-11D-A087-01,TCGA-A1-A0SP-01A-11D-A099-09,TCGA-A1-A0SP-01A-11D-A10P-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ILC-like
2,TCGA-A2-A04P,IDC,Basal,0.60,0.445335,TCGA-A2-A04P-01A-31R-A034-07,TCGA-A2-A04P-01A-31R-A035-13,TCGA-A2-A04P-01A-31D-A036-01,TCGA-A2-A04P-01A-31D-A128-09,TCGA-A2-A04P-01A-31D-A032-05,...,-0.032671,-0.725427,0.990956,-0.389598,0.047441,1.079578,NaN,NaN,NaN,NaN

In [4]:
#Number of IDC and ILC samples
data_A.groupby('Final Pathology').count()

,Case.ID,PAM50,TumorPurity,ProliferationScore,mRNA,miRNA,SNP,Exome,Methylation,RPPA,...,Hormone_a score,Hormone_b score,PI3K/Akt score,Ras/MAPK score,RTK score,TSC/mTOR score,ISOpure,OncoSign,ElasticNet,Unnamed: 27
Final Pathology,,,,,,,,,,,,,,,,,,,,,
IDC,490,490,468,490,490,490,490,490,490,393,...,393,393,393,393,393,393,0,0,0,2
ILC,127,127,107,127,127,127,127,127,127,79,...,79,79,79,79,79,79,0,0,0,0
Mixed.IDC.ILC,88,88,84,88,88,88,88,88,88,72,...,72,72,72,72,72,72,88,88,88,0
Other,112,112,100,112,112,112,112,112,112,89,...,89,89,89,89,89,89,0,0,0,0

In [6]:
#keep only the LumA type
data_A=data_A[data_A['PAM50']== 'LumA']

#keep only IDC and ILC breast cancer
cancer_type=['IDC','ILC']
data_A=data_A[data_A['Final Pathology'].isin(cancer_type)]

data_A.head(3)

,Case.ID,Final Pathology,PAM50,TumorPurity,ProliferationScore,mRNA,miRNA,SNP,Exome,Methylation,...,Hormone_a score,Hormone_b score,PI3K/Akt score,Ras/MAPK score,RTK score,TSC/mTOR score,ISOpure,OncoSign,ElasticNet,Unnamed: 27
158,TCGA-B6-A0IG,IDC,LumA,0.73,-0.568397,TCGA-B6-A0IG-01A-11R-A034-07,TCGA-B6-A0IG-01A-11R-A035-13,TCGA-B6-A0IG-01A-11D-A036-01,TCGA-B6-A0IG-01A-11W-A050-09,TCGA-B6-A0IG-01A-11D-A032-05,...,2.012295,6.472142,-3.327236,3.454363,2.743972,0.599048,NaN,NaN,NaN,NaN
159,TCGA-BH-A0HQ,IDC,LumA,0.52,-0.821974,TCGA-BH-A0HQ-01A-11R-A034-07,TCGA-BH-A0HQ-01A-11R-A035-13,TCGA-BH-A0HQ-01A-11D-A036-01,TCGA-BH-A0HQ-01A-11W-A050-09,TCGA-BH-A0HQ-01A-11D-A032-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,TCGA-A1-A0SD,IDC,LumA,0.51,-0.853940,TCGA-A1-A0SD-01A-11R-A115-07,TCGA-A1-A0SD-01A-11R-A114-13,TCGA-A1-A0SD-01A-11D-A111-01,TCGA-A1-A0SD-01A-11D-A10Y-09,TCGA-A1-A0SD-01A-11D-A112-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#selection of the case.id (patient id) that are luminal A IDC or luminal A ILC

selected_patients=data_A['Case.ID']
selected_patients

158    TCGA-B6-A0IG
159    TCGA-BH-A0HQ
160    TCGA-A1-A0SD
161    TCGA-A1-A0SF
162    TCGA-A1-A0SJ
           ...
594    TCGA-MS-A51U
595    TCGA-OL-A66K
596    TCGA-A2-A0CR
597    TCGA-A7-A13H
598    TCGA-AC-A62Y
Name: Case.ID, Length: 307, dtype: object

## 2- Extraction of the luminal A samples ID (IDC & ILC)

**AIM**: extract the samples ID with luminal A ILC or luminal A IDC.

In [9]:
# read data with clinical sample data (link between patient id and sample id)
data_sample = pd.read_csv('data/data_clinical_sample.txt',delimiter='\t',header=2,skiprows=range(0, 2))

data_sample.head(2)

,PATIENT_ID,SAMPLE_ID,OTHER_SAMPLE_ID,DAYS_TO_COLLECTION,IS_FFPE,OCT_EMBEDDED,PATHOLOGY_REPORT_FILE_NAME,SURGICAL_PROCEDURE_FIRST,FIRST_SURGICAL_PROCEDURE_OTHER,SURGERY_FOR_POSITIVE_MARGINS,...,DISEASE_CODE,METASTATIC_TUMOR_INDICATOR,PROJECT_CODE,TISSUE_SOURCE_SITE,TUMOR_TISSUE_SITE,CANCER_TYPE,CANCER_TYPE_DETAILED,ONCOTREE_CODE,SAMPLE_TYPE,SOMATIC_STATUS
0,TCGA-LQ-A4E4,TCGA-LQ-A4E4-01,8C8D4BD4-3AA9-4AD1-9715-2376EE540A0C,414,NO,TRUE,TCGA-LQ-A4E4.C13D16C9-BAC7-4CA4-B062-D925466F9...,Modified Radical Mastectomy,[Not Available],[Not Available],...,[Not Available],[Not Available],[Not Available],LQ,Breast,Invasive Breast Carcinoma,Breast Invasive Lobular Carcinoma,ILC,Primary,Matched
1,TCGA-A2-A3KC,TCGA-A2-A3KC-01,8318A9A4-E78E-4DB8-97C7-2CC733D0C512,299,NO,TRUE,TCGA-A2-A3KC.593AF241-8F84-4BA0-8878-7C1CE72A4...,Simple Mastectomy,[Not Available],[Not Available],...,[Not Available],NO,[Not Available],A2,Breast,Invasive Breast Carcinoma,Breast Invasive Lobular Carcinoma,ILC,Primary,Matched

In [10]:
#select the column of interest
data_sample=data_sample[['PATIENT_ID','SAMPLE_ID','CANCER_TYPE_DETAILED','ER_STATUS_BY_IHC','PR_STATUS_BY_IHC','IHC_HER2','ONCOTREE_CODE']]

In [11]:
#keep only the data with IDC and ILC 
data=data_sample[data_sample.ONCOTREE_CODE.isin(cancer_type)]

In [12]:
#keep only the patient with a luminal A cancer type
data=data[data.PATIENT_ID.isin(selected_patients)]

In [13]:
#list with the sample id of interest
selected_samples=data['SAMPLE_ID']

## 3- Genes expression of each selected lumA sample (IDC or ILC)

**AIM**: Filter the RNA-seq data in order to keep only samples that are classified as luminal A ILC or luminal A IDC.

In [14]:
# read data with rppa data
data_seq = pd.read_csv('data2/data_RNA_Seq_v2_expression_median.txt',delimiter='\t')
data_seq.head(2)

,Hugo_Symbol,Entrez_Gene_Id,TCGA-A1-A0SB-01,TCGA-A1-A0SD-01,TCGA-A1-A0SE-01,TCGA-A1-A0SF-01,TCGA-A1-A0SH-01,TCGA-A1-A0SI-01,TCGA-A1-A0SJ-01,TCGA-A1-A0SK-01,...,TCGA-LL-A5YM-01,TCGA-LL-A5YN-01,TCGA-LL-A5YO-01,TCGA-LL-A5YP-01,TCGA-LQ-A4E4-01,TCGA-MS-A51U-01,TCGA-OL-A66H-01,TCGA-OL-A66I-01,TCGA-OL-A66J-01,TCGA-OL-A66K-01
0,UBE2Q2P2,100134869,14.3935,11.3241,4.4426,10.7401,3.0048,2.9782,4.9419,28.8560,...,0.0000,2.9624,3.6899,6.3020,14.1288,7.9343,2.2519,1.2603,5.0428,4.3892
1,HMGB1P1,10357,116.3870,60.2630,153.1452,141.1933,79.8003,63.5491,134.8733,1119.1932,...,101.2865,100.3083,278.5626,206.4376,117.0300,150.6834,115.3378,158.3599,124.6327,106.3475

In [15]:
#new dataframe with only the lumA+ samples
data_seq = data_seq[data_seq.columns.intersection(selected_samples)]

data_seq.head(3)

,TCGA-A1-A0SD-01,TCGA-A1-A0SE-01,TCGA-A1-A0SF-01,TCGA-A1-A0SJ-01,TCGA-A1-A0SM-01,TCGA-A1-A0SQ-01,TCGA-A2-A04V-01,TCGA-A2-A0CK-01,TCGA-A2-A0CO-01,TCGA-A2-A0CP-01,...,TCGA-GM-A3NW-01,TCGA-GM-A3NY-01,TCGA-GM-A3XG-01,TCGA-GM-A3XN-01,TCGA-GM-A4E0-01,TCGA-LL-A440-01,TCGA-LL-A5YN-01,TCGA-LQ-A4E4-01,TCGA-MS-A51U-01,TCGA-OL-A66K-01
0,11.3241,4.4426,10.7401,4.9419,7.6484,1.0368,5.2638,2.6384,6.4292,4.5107,...,6.8182,7.4766,2.0821,6.7566,2.0267,13.1811,2.9624,14.1288,7.9343,4.3892
1,60.2630,153.1452,141.1933,134.8733,119.4760,41.5532,166.4412,113.6646,97.5164,96.5147,...,79.6378,116.2669,144.9050,175.5820,148.0796,136.0213,100.3083,117.0300,150.6834,106.3475
2,83.6986,74.7018,314.4482,63.6488,80.8081,75.8447,132.8173,263.0303,281.5666,247.3190,...,237.9897,453.7262,336.9480,601.4904,917.1449,708.0590,367.2936,307.2124,540.4278,554.5539

In [13]:
#data_seq.to_csv('data/seq.csv')

## 4- Extraction of the samles ID and respective histological subtype

**AIM:** Extract the sample ID and histological subtype of the remaining samples in the RNA-seq data.

In [15]:
data_B=data_sample[['SAMPLE_ID','ONCOTREE_CODE']]

In [16]:
data_t=data_seq.T

In [17]:
data_t.reset_index(inplace=True)

In [18]:
data_B=pd.merge(data_B, data_t, left_on='SAMPLE_ID',right_on='index')

In [19]:
data_B=data_B[['SAMPLE_ID','ONCOTREE_CODE']]

In [23]:
data_B.groupby('group').count()

       SAMPLE_ID
group
IDC          200
ILC          106

In [20]:
data_B.rename(columns={'ONCOTREE_CODE':'group'},inplace=True)

In [21]:
#data_B.to_csv('data/seq_samples.csv')